version: "3"

vars:
  DEST: ./bin
  OUT: gait

tasks:
  default:
    deps: [build]

  build:
    desc: "Build application into binary"
    cmd: go build -o {{.DEST}}/{{.OUT}}
    silent: true

  run:
    desc: "Run application"
    deps: [build]
    cmds:
      - "{{.DEST}}/{{.OUT}} {{.CLI_ARGS}}"
    silent: true
