version: "3"

vars:
  DEST: ./bin
  OUT: gait

tasks:
  default:
    deps: [run]

  clean:
    desc: "Removes the {{.DEST}} directory"
    cmd: rm -r {{.DEST}}/
    silent: true

  build:
    desc: "Build application into binary"
    deps: [clean]
    cmd: go build -o {{.DEST}}/{{.OUT}}
    silent: true

  run:
    desc: "Run application"
    deps: [build]
    cmds:
      - "{{.DEST}}/{{.OUT}}"
    silent: true
